export const JOIN_ITEM = 'JOIN_ITEM';
export const JOIN_CANCEL = 'JOIN_CANCEL';
export const JOIN_SAVE_DISCORD_DETAILS = 'JOIN_SAVE_DISCORD_DETAILS';
export const JOIN_SAVE_PAYMENT_METHOD = 'JOIN_SAVE_PAYMENT_METHOD';
